language: node_js

node_js:
  - "12"

dist: trusty
sudo: required
addons:
  chrome: stable

before_install:
  - npm i -g npm@6.9.0

cache: npm

script:
  - npm run lerna:lint
  - npm run lerna:test:ci
  - npm run lerna:build

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
  script: npm run lerna:publish:ci
  skip_cleanup: true
  on:
    branch: master
    tags: true
